version: '3.5'

services:
  db_financial:
    container_name: db_financial
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=dev
      - APP_DB_PASS=dev
      - FINANCIAL_DB_NAME=financial_database
    ports:
      - 54323:5432
    volumes:
      - ./db_scripts:/docker-entrypoint-initdb.d
    networks:
      - db_net_3
  financial-service:
    container_name: financial-service
    image: financial-service:latest
    environment:
      - APP_SERVICES_BALANCESERVICE_HOST=http://balance-service:8081
      - APP_SERVICES_ACCOUNTSERVICE_HOST=http://account-service:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_financial:5432/financial_database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_RABBITMQ_HOST=rabbitmq
    build:
      context: .  
    ports:
      - 8090:8090
    restart: always  
    networks:
      - db_net_3
      - services_net
      - rabbit_net
    depends_on:
      - db_financial
networks:
  db_net_3:
    name: db_net_3
  services_net:
    external: true
  rabbit_net:
    external: true
   