app:
  name: FinancialService
  services:
    BalanceService:
      name: BalanceService
      host: http://localhost:8081
    AccountService:
      name: AccountService
      host: http://localhost:8080
server:
  port : 8090
spring:
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/financial_database
    username: ad
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
